celltype_dict = {
    "t cell": [
        "naive thymus-derived cd4-positive, alpha-beta t cell",
        "naive thymus-derived cd8-positive, alpha-beta t cell",
        "cd4-positive helper t cell",
        "cd4-positive, alpha-beta memory t cell",
        "cd4-positive, alpha-beta t cell",
        "cd8-positive, alpha-beta memory t cell",
        "thymocyte",
        "t cell",
        "regulatory t cell",
        "cd8-positive, alpha-beta t cell",
    ],
    "dendritic cell": [
        "conventional dendritic cell",
        "cd1c-positive myeloid dendritic cell",
        "cd141-positive myeloid dendritic cell",
        "plasmacytoid dendritic cell",
        "dendritic cell",
    ],
    "b cell": ["memory b cell", "naive b cell", "b cell"],
    "plasma cell": ["plasma cell"],
    "monocyte": [
        "classical monocyte",
        "intermediate monocyte",
        "monocyte",
        "non-classical monocyte",
    ],
    "macrophage": [
        "macrophage",
    ],
    "erythrocyte": [
        "erythrocyte",
        "erythroid progenitor cell",
    ],
    "innate lymphoid cell": [
        "immature natural killer cell",
        "innate lymphoid cell",
        "mature nk t cell",
        "natural killer cell",
    ],
    "hematopoietic stem cell": ["hematopoietic stem cell"],
    "mast cell": ["mast cell"],
    "platelet": ["platelet"],
    "granulocyte": [
        "basophil",
        "neutrophil",
    ],
    "myeloid cell": ["myeloid cell"],
    "intestinal epithelial cell": [
        "enterocyte",
        "enterocyte of epithelium of large intestine",
        "enterocyte of epithelium of small intestine",
        "intestinal crypt stem cell",
        "intestinal enteroendocrine cell",
        "transit amplifying cell of small intestine",
        "transit amplifying cell of large intestine",
        "paneth cell of epithelium of small intestine",
        "paneth cell of epithelium of large intestine",
        "duodenum glandular cell",
        "immature enterocyte",
        "mature enterocyte",
        "intestinal tuft cell",
    ],
    "ciliated cell": ["ciliated cell"],
    "epithelial cell of lung": [
        "pulmonary ionocyte",
        "club cell",
        "basal cell",
        "goblet cell",
        "type ii pneumocyte",
        "type i pneumocyte",
        "lung ciliated cell",
        "serous cell of epithelium of bronchus",
        "respiratory goblet cell",
    ],
    "mesothelial cell": ["mesothelial cell"],
    "epithelial cell": ["epithelial cell"],
    "secretory cell": ["secretory cell"],
    "pancreatic endocrine cell": [
        "pancreatic alpha cell",
        "pancreatic delta cell",
        "pancreatic pp cell",
        "pancreatic beta cell",
    ],
    "pancreatic acinar cell": ["pancreatic acinar cell"],
    "pancreatic ductal cell": ["pancreatic ductal cell"],
    "kidney epithelial cell": ["kidney epithelial cell"],
    "bladder urothelial cell": ["bladder urothelial cell"],
    "kidney epithelial cell": ["kidney epithelial cell"],
    "medullary thymic epithelial cell": ["medullary thymic epithelial cell"],
    "capillary aerocyte": ["capillary aerocyte"],
    "capillary endothelial cell": ["capillary endothelial cell"],
    "endothelial cell": ["endothelial cell"],
    "endothelial cell of artery": ["endothelial cell of artery"],
    "endothelial cell of lymphatic vessel": ["endothelial cell of lymphatic vessel"],
    "endothelial cell of vascular tree": ["endothelial cell of vascular tree"],
    "gut endothelial cell": ["gut endothelial cell"],
    "lung microvascular endothelial cell": ["lung microvascular endothelial cell"],
    "vein endothelial cell": ["vein endothelial cell"],
    "connective tissue cell": [
        "connective tissue cell",
        "adventitial cell",
        "alveolar fibroblast",
        "myofibroblast cell",
        "fibroblast",
        "pancreatic stellate cell",
    ],
    "tendon cell": ["tendon cell"],
    "muscle cell": [
        "bronchial smooth muscle cell",
        "fast muscle cell",
        "vascular associated smooth muscle cell",
        "smooth muscle cell",
        "skeletal muscle satellite stem cell",
        "slow muscle cell",
        "pericyte cell",
    ],
    "mesenchymal stem cell": ["mesenchymal stem cell"],
}
