compartment_dict = {
    'Immune':['basophil',
              'b cell',
              'classical monocyte',
              'cd4-positive helper t cell',
              'cd4-positive, alpha-beta memory t cell',
              'cd4-positive, alpha-beta t cell',
              'cd8-positive, alpha-beta memory t cell',
              'cd8-positive, alpha-beta t cell',
              'conventional dendritic cell',
              'cd1c-positive myeloid dendritic cell',
              'cd141-positive myeloid dendritic cell', 
              'dendritic cell',
              'erythrocyte', 
              'erythroid progenitor cell',
              'hematopoietic stem cell', 
              'immature natural killer cell',
              'innate lymphoid cell', 
              'intermediate monocyte',
              'macrophage', 
              'mast cell',
              'mature nk t cell',
              'memory b cell',  
              'naive b cell',
              'monocyte', 
              'myeloid cell', 
              'naive thymus-derived cd4-positive, alpha-beta t cell',
              'naive thymus-derived cd8-positive, alpha-beta t cell',
              'natural killer cell', 
              'neutrophil', 
              'non-classical monocyte',
              'thymocyte',
              't cell', 
              'platelet', 
              'regulatory t cell',
              'plasma cell', 
              'plasmacytoid dendritic cell',],
    'Epithelial':['mesothelial cell',
                  'pulmonary ionocyte',
                  'ciliated cell',
                  'club cell',
                  'basal cell',
                  'bladder urothelial cell',
                  'duodenum glandular cell', 
                  'enterocyte of epithelium of large intestine',
                  'enterocyte of epithelium of small intestine', 
                  'epithelial cell','goblet cell',
                  'intestinal crypt stem cell', 
                  'intestinal enteroendocrine cell',
                  'transit amplifying cell of small intestine',
                  'transit amplifying cell of large intestine',
                  'kidney epithelial cell', 
                  'lung ciliated cell',
                  'paneth cell of epithelium of small intestine', 
                  'paneth cell of epithelium of large intestine',
                  'type ii pneumocyte',
                  'medullary thymic epithelial cell',
                  'pancreatic alpha cell', 
                  'pancreatic acinar cell', 
                  'pancreatic delta cell',
                  'pancreatic ductal cell', 
                  'pancreatic pp cell',
                  'type i pneumocyte',
                  'pancreatic beta cell',
                  'secretory cell', 
                  'serous cell of epithelium of bronchus',
                  'immature enterocyte',
                  'mature enterocyte',
                  'intestinal tuft cell',
                  'respiratory goblet cell', ],
    'Endothelial':['capillary aerocyte',
                   'capillary endothelial cell',
                   'endothelial cell',
                   'endothelial cell of artery',
                   'endothelial cell of lymphatic vessel',
                   'endothelial cell of vascular tree',
                   'gut endothelial cell', 
                   'lung microvascular endothelial cell',
                   'vein endothelial cell'],
    'Stromal':[ 'adventitial cell',
               'connective tissue cell', 
               'bronchial smooth muscle cell', 
               'alveolar fibroblast', 
               'fast muscle cell',
               'mesenchymal stem cell',
               'vascular associated smooth muscle cell', 
               'tendon cell',
               'smooth muscle cell',
               'skeletal muscle satellite stem cell',
               'slow muscle cell', 
               'pericyte cell', 
               'myofibroblast cell', 
               'fibroblast', 
               'pancreatic stellate cell',  ]
}
